/* ── Game Workspace Report Builder (v0.9.5) ── */
/* Builds a Markdown report of the current game workspace state */
/* Pure function — no file I/O, no side effects */

import type {
  GameWorkspaceSummary,
  GameWorkspaceDashboard,
  GameWorkspaceEntry,
  GameDocType,
} from '../types';

export interface ReportInput {
  summary: GameWorkspaceSummary;
  dashboard: GameWorkspaceDashboard;
  entries: GameWorkspaceEntry[];
  generatedAt: string;
  vaultName?: string;
}

/* ── Helpers ── */

const DOC_TYPE_LABELS: Record<GameDocType, string> = {
  gdd: 'GDD',
  worldbuilding: 'Worldbuilding',
  story: 'Story / Plot',
  dialogue: 'Dialogue',
  performance: 'Performance / Cutscenes',
  character: 'Characters',
  item: 'Items',
  quest: 'Quests',
  taskTable: 'Task Tables',
  unityTask: 'Unity Tasks',
  devlog: 'Devlog',
};

function entryRow(entry: GameWorkspaceEntry): string {
  const parts: string[] = [];
  parts.push(`- **${entry.title}**`);
  parts.push(`  \`${entry.relativePath}\``);
  if (entry.status) parts.push(`  Status: ${entry.status}`);
  if (entry.priority) parts.push(`  Priority: ${entry.priority}`);
  if (entry.owner) parts.push(`  Owner: ${entry.owner}`);
  if (entry.updatedAt) parts.push(`  Updated: ${entry.updatedAt}`);
  if (entry.tags.length > 0) parts.push(`  Tags: ${entry.tags.join(', ')}`);
  return parts.join('\n');
}

function sectionEntries(title: string, entries: GameWorkspaceEntry[]): string {
  if (entries.length === 0) return '';
  const lines: string[] = [`## ${title}`, ''];
  for (const entry of entries) {
    lines.push(entryRow(entry));
  }
  lines.push('');
  return lines.join('\n');
}

/* ── Main builder ── */

export function buildGameWorkspaceReportMarkdown(input: ReportInput): string {
  const { summary, dashboard, entries, generatedAt, vaultName } = input;
  const lines: string[] = [];

  /* Header */
  lines.push('# Game Workspace Report');
  lines.push('');
  if (vaultName) {
    lines.push(`> **Vault**: ${vaultName}`);
    lines.push('');
  }

  /* Project Summary */
  lines.push('## Project Summary');
  lines.push('');
  lines.push('| Metric | Count |');
  lines.push('|--------|-------|');
  lines.push(`| Total Game Docs | ${summary.totalGameDocs} |`);
  lines.push(`| GDD | ${summary.gddCount} |`);
  lines.push(`| Worldbuilding | ${summary.worldbuildingCount} |`);
  lines.push(`| Story / Plot | ${summary.storyCount} |`);
  lines.push(`| Dialogue | ${summary.dialogueCount} |`);
  lines.push(`| Performance / Cutscenes | ${summary.performanceCount} |`);
  lines.push(`| Characters | ${summary.characterCount} |`);
  lines.push(`| Items | ${summary.itemCount} |`);
  lines.push(`| Quests | ${summary.questCount} |`);
  lines.push(`| Task Tables | ${summary.taskTableCount} |`);
  lines.push(`| Unity Tasks | ${summary.unityTaskCount} |`);
  lines.push(`| Devlog | ${summary.devlogCount} |`);
  lines.push(`| Draft | ${summary.draftCount} |`);
  lines.push(`| Done | ${summary.doneCount} |`);
  lines.push(`| High Priority | ${summary.highPriorityCount} |`);
  lines.push(`| Missing Core Docs | ${dashboard.missingCoreDocs.length} |`);
  lines.push('');

  /* Missing Core Docs */
  if (dashboard.missingCoreDocs.length > 0) {
    lines.push('## Missing Core Docs');
    lines.push('');
    for (const docType of dashboard.missingCoreDocs) {
      lines.push(`- No ${DOC_TYPE_LABELS[docType]} found`);
    }
    lines.push('');
  }

  /* Quick sections */
  lines.push(sectionEntries('High Priority Docs', dashboard.highPriorityEntries));
  lines.push(sectionEntries('Draft Docs', dashboard.draftEntries));
  lines.push(sectionEntries('Recently Updated', dashboard.recentlyUpdatedEntries));
  lines.push(sectionEntries('Missing Metadata', dashboard.missingMetadataEntries));

  /* All Game Docs grouped by type */
  lines.push('## All Game Docs');
  lines.push('');

  const types: GameDocType[] = ['gdd', 'worldbuilding', 'story', 'dialogue', 'performance', 'character', 'item', 'quest', 'taskTable', 'unityTask', 'devlog'];
  for (const docType of types) {
    const groupEntries = entries.filter((e) => e.type === docType);
    if (groupEntries.length === 0) continue;

    lines.push(`### ${DOC_TYPE_LABELS[docType]} (${groupEntries.length})`);
    lines.push('');
    for (const entry of groupEntries) {
      lines.push(entryRow(entry));
    }
    lines.push('');
  }

  /* Footer */
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by Ars-note Game Workspace at ${generatedAt}*`);
  lines.push('');

  return lines.join('\n');
}
